server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reviews
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: review-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"